version: "3.4"
services:
  devpisrv:
    build: .
    ports:
      - "${SERVER_IP:-0.0.0.0}:${SERVER_PORT:-3141}:3141"
    volumes:
      - devpisrv-data:/var/local/devpisrv
    restart: always
volumes:
  devpisrv-data:
